set nocompatible

" Pathogien
    call pathogen#infect()
    call pathogen#helptags()

" Terminal
    set term=screen-256color
    set t_Co=256
    set ttyfast
    set shell=zsh

" Encoding
set termencoding=utf-8
set encoding=utf-8      " Yea baby. Its the 21st century

" Indentation
    filetype plugin indent on
    syntax on
        set autoindent
    set smartindent
    set expandtab                   " Fuck tabs. Uses spaces
    set wrap                        " I wrap up my shit. You should too
    set cc=+1

" Text settings
    set textwidth=80                       " Max text width
    set tabstop=4                        " numbers of spaces of tab character
    set shiftwidth=4                       " numbers of spaces to (auto)indent
    set showcmd                     " display incomplete commands

" Search
    set hlsearch                    " highlight searches
    set incsearch                   " do incremental searching

" Notifications
    set report=0                    " Tell me how many lines commands change
    set number                      " show line numbers
    set ruler                       " show the cursor position all the time
    set ls=2                        " always show status line

" Folds
    set foldenable                  " Yes. Folding
    set foldmethod=indent           " My files are always neatly indented
    set foldlevel=100               " Don't autofold

" Backup files - Nah!
    set nobackup                    " do not keep backup files
    set noswapfile                  " do not write annoying swap files

" Misc Behaviour
    set backspace=eol,start,indent

" Mapping.
    " Fn Keys Mapping
        map <F3> :RainbowParenthesesToggle<CR>

    " Leader Key Mapping
        map <leader>i gg=G              " \i Mass indent
        map <leader>v :tabe $MYVIMRC<CR>" \v Open vimrc
        map <leader>V :so $MYVIMRC<CR>  " \V Reload vimrc
        map <leader>w :w!<cr>           " \w Save
        map <leader>pp :setlocal paste!<CR>" \pp Toggle paste mode on and off
        " Git specific (requires vim-fugitive)
            map <leader>gs :Gstatus<CR>
            map <leader>gd :Gdiff<CR>
            map <leader>gc :Gcommit<CR>
            map <leader>gl :Glog<CR>
            map <leader>gp :Git push<CR>

    " Space Key Mapping
        nmap <space> <c-d>

    " Ctrl Key Mapping
        map <c-S-a> ^
        map <c-S-e> %

" ColorSchemes
    set cul
    hi CursorLine term=none cterm=none ctermbg=3
    set background=dark
    let g:solarized_termtrans=1
    let g:solarized_termcolors=256
    let g:solarized_contrast="high"
    let g:solarized_visibility="high"
    let g:jellybeans_use_lowcolor_black = 1
    colorscheme jellybeans

" Vim-indent-guides
let g:indent_guides_color_change_percent = 30
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=steelblue3 ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=ivory3 ctermbg=4

" Custom Fn calls
autocmd BufWrite * :call DeleteTrailingWS()

" Misc Fn defs
func! DeleteTrailingWS()
      exe "normal mz"
        %s/\s\+$//ge
          exe "normal `z"
      endfunc
