alias .4="cd ../../../"
alias .5="cd ../../../../"
alias c="pbcopy"
alias df="df -h"
alias echo="echo -e"
alias esearch="/usr/share/elasticsearch/bin/elasticsearch"
alias gemin="sudo gem install"
alias gds="git diff --staged"
alias glog="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset \
%s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glp="git log --pretty=oneline"
alias gls="git log --pretty=short"
alias grb="git rebase"
alias grbd="git rebase devel"
alias inst="sudo apt-get install"
alias l="less"
alias netusage="sudo vnstat -u -i wlan0 && sudo vnstat -i wlan0"
alias off="sudo poweroff"
alias pbcopy='xclip -selection clipboard'
alias pipin="sudo pip install"
alias pipun="sudo pip uninstall"
alias purge="sudo apt-get purge"
alias py="python"
alias py3="python3"
alias rasp="ssh pi@rasp"
alias reboot="sudo reboot"
alias rf="rm -rf"
alias rgrep="rgrep --exclude-dir=.git --exclude-dir=env --exclude-dir=node_modules"
alias rm="rm -i"
alias screenoff="xset dpms force off"
alias sudo='sudo '
alias sz="source ~/.zshrc"
alias tree="tree -I '.git|env|node_modules|*.pyc|bower_components'"
alias updt="sudo apt-get update"
alias v="vim"
alias vxc="vim ~/.vimrc"
alias zxc="vim ~/.zshrc"
